permissions:
    contents: write
name: Manual Build and Deploy PowerMonitor API

on:
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0

            - name: Set up Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: '20'

            - name: Install dependencies
              run: npm ci

            - name: Lint
              run: npm run lint

            - name: Run tests
              run: npm run test

            - name: Check version bump eligibility
              id: version-check
              run: |
                  VERSION=$(node -p "require('./package.json').version")
                  # Skip bump if version ends with .0 or .0.0
                  if echo "$VERSION" | grep -Eq '^[0-9]+\.[0-9]+\.0$|^[0-9]+\.0\.0$'; then
                    echo "bump=false" >> $GITHUB_OUTPUT
                  else
                    echo "bump=true" >> $GITHUB_OUTPUT
                  fi

            - name: Bump version
              if: steps.version-check.outputs.bump == 'true'
              run: npm version patch --no-git-tag-version

            - name: Replace build
              run: node ./replace.build.js

            - name: Check versions
              run: npm run test tests/shared/version-consistency.spec.ts

            - name: Build
              run: tsc -p tsconfig.build.prod.json

            - name: Configure git
              run: |
                  git config user.name "github-actions[bot]"
                  git config user.email "github-actions[bot]@users.noreply.github.com"

            - name: Commit and push version bump, lockfile, and environments
              run: |
                  VERSION=$(node -p "require('./package.json').version")
                  git fetch --prune --unshallow || true
                  git checkout master
                  git add package.json package-lock.json src/config/environments.ts
                  git commit -m "[skip ci] $VERSION" || echo "No changes to commit"
                  git tag v$VERSION
                  git push origin master
                  git push origin v$VERSION

            - name: Archive dist and package files
              run: |
                  zip -r powermonitor-api.zip dist package.json package-lock.json

            - name: Upload artifact
              uses: actions/upload-artifact@v4
              with:
                  name: powermonitor-api-artifact
                  path: powermonitor-api.zip

    deploy:
        runs-on: [self-hosted, linux, arm]
        needs: build
        steps:
            - name: Download artifact
              uses: actions/download-artifact@v4
              with:
                  name: powermonitor-api-artifact

            - name: Stop PM2 app
              run: |
                  sudo -u pi pm2 stop PowerMonitor || true

            - name: Remove old dist folder
              run: |
                  sudo -u pi rm -rf /home/pi/PowerMonitor.API/dist

            - name: Unpack archive to target
              run: |
                  sudo -u pi unzip -o powermonitor-api.zip -d /home/pi/PowerMonitor.API

            - name: Install dependencies on target
              run: |
                  cd /home/pi/PowerMonitor.API && sudo -u pi npm ci --omit=dev

            - name: Start PM2 app
              run: |
                  sudo -u pi pm2 start /home/pi/PowerMonitor.API/ecosystem.config.js --only PowerMonitor
